# Generated by Django 6.0.3 on 2026-04-07 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0002_chord_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chord",
            name="image",
        ),
        migrations.CreateModel(
            name="ChordImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="chord_images/")),
                (
                    "chord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="testApp.chord",
                    ),
                ),
            ],
        ),
    ]
